#!/usr/bin/env python3
from __future__ import annotations
import argparse,html,json
from pathlib import Path
import yaml
from jsonschema import Draft202012Validator
ROOT=Path(__file__).resolve().parents[1]
CSS='''
:root{font-family:Inter,ui-sans-serif,system-ui,sans-serif;color:#171717;background:#f4f4f2}*{box-sizing:border-box}body{margin:0;padding:32px}.wrap{max-width:1400px;margin:auto}h1{font-size:30px;margin:0 0 8px}.decision{color:#555;margin:0 0 26px}.options{display:grid;grid-template-columns:repeat(auto-fit,minmax(360px,1fr));gap:22px}.card{background:white;border:1px solid #d9d9d4;border-radius:16px;padding:20px;box-shadow:0 8px 30px rgba(0,0,0,.05)}.meta{min-height:92px}.summary{color:#444}.tradeoff{font-size:13px;color:#666;border-top:1px solid #eee;padding-top:10px}.wire{display:grid;grid-template-columns:repeat(12,1fr);gap:8px;background:#f7f7f5;border:1px solid #e4e4df;border-radius:12px;padding:10px;margin-top:16px}.region{border:1px solid #c9c9c2;border-radius:8px;padding:10px;display:flex;align-items:center;justify-content:center;text-align:center;font-size:12px;background:#fff}.h-small{min-height:48px}.h-medium{min-height:90px}.h-large{min-height:150px}.e-high{border-width:2px;font-weight:700;background:#f0f0ec}.e-medium{font-weight:600}.foot{margin-top:24px;font-size:13px;color:#666}
'''
def main()->int:
    ap=argparse.ArgumentParser(); ap.add_argument('input'); ap.add_argument('--output',default='visual-options.html'); args=ap.parse_args()
    ip=Path(args.input); data=yaml.safe_load(ip.read_text(encoding='utf-8')) if ip.suffix.lower() in {'.yaml','.yml'} else json.loads(ip.read_text(encoding='utf-8'))
    schema=json.loads((ROOT/'schemas/visual-options.schema.json').read_text(encoding='utf-8')); errors=list(Draft202012Validator(schema).iter_errors(data))
    if errors:
        for e in errors: print(f'ERROR at {list(e.path)}: {e.message}')
        return 1
    cards=[]
    for option in data['options']:
        regions=''.join(f'''<div class="region h-{html.escape(r['height'])} e-{html.escape(r['emphasis'])}" style="grid-column:span {r['span']}">{html.escape(r['label'])}</div>''' for r in option['regions'])
        cards.append(f'''<article class="card"><div class="meta"><h2>{html.escape(option['title'])}</h2><p class="summary">{html.escape(option['summary'])}</p><p class="tradeoff">{html.escape(option['tradeoff'])}</p></div><div class="wire">{regions}</div></article>''')
    doc=f'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{html.escape(data['title'])}</title><style>{CSS}</style></head><body><main class="wrap"><h1>{html.escape(data['title'])}</h1><p class="decision">{html.escape(data['decision'])}</p><section class="options">{''.join(cards)}</section><p class="foot">Generated by Discovery visual validation. Use this artifact to criticize structure and hierarchy, not to approve final visual polish.</p></main></body></html>'''
    out=Path(args.output); out.write_text(doc,encoding='utf-8'); print(out); return 0
if __name__=='__main__': raise SystemExit(main())
